function [Nmat, rhoData] = build_nonlinear_operator( ...
u, n_dofs_nurbs, pw_dofs_indices, ...
    nurbs_original, nurbs_refine, n_gp, ...
    k_pw, L, a, m_pw)

% Build the nonlinear operator from the current density.
rhoData = compute_density_samples( ...
    u, n_dofs_nurbs, pw_dofs_indices, ...
    nurbs_original, nurbs_refine, n_gp, ...
    k_pw, L, a, m_pw);

N_in = assemble_nonlinear_nurbs( ...
    nurbs_original, nurbs_refine, rhoData.rho_in, n_gp);

N_pw = assemble_nonlinear_pw_from_grid( ...
    k_pw, rhoData.rho_pw, L);

n_total = max([n_dofs_nurbs; pw_dofs_indices(:)]);

Nmat = sparse(n_total, n_total);
Nmat(1:n_dofs_nurbs, 1:n_dofs_nurbs) = N_in;
Nmat(pw_dofs_indices, pw_dofs_indices) = N_pw;

Nmat = 0.5 * (Nmat + Nmat');
end
