function out = run_vout_2048_simple()
%Run VOUT 2048 simple.

activate_example_workflow('vout_fourier', {'config', 'core', 'operators', 'solver'});

masked = test_vout_fourier_3d(struct( ...
    'Nc', 20, ...
    'fft_grid_n', 2048, ...
    'fft_precision', 'single', ...
    'cheb_n', 80, ...
    'n_ref', 192, ...
    'tag', 'masked_m2048_single', ...
    'methods', {{'Masked FFT'}}, ...
    'memory_peak_factor', 1.0, ...
    'memory_free_fraction', 0.98));

cheb = test_vout_fourier_3d(struct( ...
    'Nc', 20, ...
    'fft_grid_n', 300, ...
    'fft_precision', 'double', ...
    'cheb_n', 80, ...
    'n_ref', 192, ...
    'tag', 'cheb_m300_n80_double', ...
    'methods', {{'FFT-Chebyshev'}}, ...
    'memory_peak_factor', 1.35, ...
    'memory_free_fraction', 0.85));

T = [masked.table; cheb.table];
outFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), ...
    'result', 'VoutFourier', 'vout_2048_simple_summary.csv');
writetable(T, outFile);

out = struct('table', T, 'csv', outFile);
end
