function outputs = plot_comparison()
% Plot energy error against DOF and elapsed time.

% Resolve the comparison data and output paths.
exampleDir = fileparts(fileparts(mfilename('fullpath')));
resultDir = fullfile(exampleDir, 'data', 'result', 'hartree_comparison');
plotDir = fullfile(resultDir, 'plots');
if ~isfolder(plotDir)
    mkdir(plotDir);
end

% Load the retained rows and separate the two methods.
comparison = readtable(fullfile(resultDir, 'comparison.csv'), ...
    'TextType', 'string');
iga = comparison(comparison.method == "IGA-PW", :);
dg = comparison(comparison.method == "DG-PW", :);
assert(height(iga) == 4 && height(dg) == 4, ...
    'The plot needs four rows from each method.');

% Prepare the error, DOF, and timing coordinates.
energyError = [iga.energyError, dg.energyError];
dof = [iga.nDof, dg.nDof];
elapsedTime = [iga.totalTime, dg.totalTime];

assert(all(isfinite(energyError(:))) && all(energyError(:) > 0), ...
    'Energy errors must be finite and positive for logarithmic axes.');
assert(all(isfinite(dof(:))) && all(dof(:) > 0), ...
    'Degrees of freedom must be finite and positive for logarithmic axes.');
assert(all(isfinite(elapsedTime(:))) && all(elapsedTime(:) > 0), ...
    'Elapsed times must be finite and positive for logarithmic axes.');

labels = {'IGA-PW', 'DG-PW'};

% Draw the DOF and elapsed-time comparisons.
[dofFigure, dofPdf] = draw_loglog_figure( ...
    dof, energyError, 'Degrees of freedom', labels, plotDir, ...
    'error_dof');
[timeFigure, timePdf] = draw_loglog_figure( ...
    elapsedTime, energyError, 'Time (s)', labels, plotDir, ...
    'error_time');

outputs = struct( ...
    'dofFigure', dofFigure, ...
    'timeFigure', timeFigure, ...
    'dofPdf', dofPdf, ...
    'timePdf', timePdf);
end

function [fig, pdfPath] = draw_loglog_figure( ...
    xData, yData, xLabelText, labels, plotDir, fileStem)

% Draw and export one log-log comparison figure.
% Apply a common style to both method curves.
colors = [223, 122, 94; 60, 64, 91] / 255;
markers = {'o', 's'};

fig = figure( ...
    'Color', 'w', ...
    'Units', 'inches', ...
    'Position', [1, 1, 4.8, 3.0], ...
    'Visible', 'off');
ax = axes(fig, ...
    'Position', [0.14, 0.16, 0.82, 0.76], ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'LineWidth', 1.0, ...
    'TickDir', 'out', ...
    'XMinorTick', 'off', ...
    'YMinorTick', 'off', ...
    'Box', 'on');

curves = loglog(ax, xData, yData, '-');
for k = 1:numel(curves)
    set(curves(k), ...
        'Color', colors(k, :), ...
        'LineWidth', 1.8, ...
        'Marker', markers{k}, ...
        'MarkerSize', 8, ...
        'MarkerFaceColor', 'w', ...
        'MarkerEdgeColor', colors(k, :));
end

grid(ax, 'off');
xlabel(ax, xLabelText, ...
    'FontName', 'Times New Roman', 'FontSize', 13);
ylabel(ax, '$|E-E_{\mathrm{ref}}|$', ...
    'Interpreter', 'latex', 'FontSize', 13);
legend(ax, curves, labels, ...
    'Location', 'southwest', ...
    'FontName', 'Times New Roman', ...
    'FontSize', 11, ...
    'Box', 'off', ...
    'Interpreter', 'none');

xlim(ax, [min(xData(:)) / 1.25, max(xData(:)) * 1.25]);
ylim(ax, [min(yData(:)) / 2, max(yData(:)) * 2]);
set(fig, 'PaperPositionMode', 'auto');
drawnow;

% Export the figure as a vector PDF.
pdfPath = fullfile(plotDir, [fileStem, '.pdf']);
exportgraphics(fig, pdfPath, 'ContentType', 'vector');
end
